# Generated by Django 4.2.29 on 2026-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='goods_front_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='封面图链接'),
        ),
    ]
