# Generated by Django 5.2 on 2026-03-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
