# Generated by Django 5.2 on 2026-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_category_is_delete_product_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
    ]
