# Generated by Django 5.2 on 2026-03-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否逻辑删除'),
        ),
    ]
